<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Throwing exceptions to generators</title>
  </head>
  <body>
    <script>
      function* NinjaGenerator() {
        try {
          yield "Hattori";
          console.log("the expected exception didn't occur");
        } catch (e) {
          console.log(e === "Catch this!", "Aha! we caught an exception");
        }
      }
      const ninjaIterator = NinjaGenerator();
      const result1 = ninjaIterator.next();
      console.log(result1.value === "Hattori"); // true
      ninjaIterator.throw("Catch this!");
    </script>
  </body>
</html>
