<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Chaining a catch method</title>
  </head>
  <body>
    <script>
      const promise = new Promise((resolve, reject) => {
        reject("thy shalt be rejected");
      });

      promise
        .then(() => console.log("this will not run"))
        .catch((err) => console.log(err));
    </script>
  </body>
</html>
